### ISSUE TITLE
Uploading videos

### ISSUE THREAD

**Issue by tomstibor** [dsasko/strapi-provider-upload-imagekit#4]
Hello,
imagekit.io supports videos like .mp4 or .mov.
If i upload video directly to imagekit.io dashboard everything works but when I upload video in Strapi, there is some issue.

Could you please look at it?

Thank you very much for your good work! 👍

**Comment by dsasko** [comment]
@tomstibor Thanks for reporting the issue. I will look into it.

**Comment by dsasko** [comment]
@tomstibor The issue should be resolved now.

For future reference:
The issue was that the name of the file didn't contain an extension (.mp4 in our case)
Imagekit doesn't know what content-type header to send for files like that so it defaults to an image.

Please update to v0.2.1 and let me know if you find any more issues

**Comment by tomstibor** [comment]
It works like a charm now, thank you very much. 👍
